import type { Metadata } from "next";
import PublicHeader from "@/components/layouts/PublicHeader";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PublicHeader />
      {children}
    </>
  );
}
